title: "Wentao Dong"
description: "Research in privacy-preserving computation and systems security."
url: "https://dongdongdoge.github.io"
repository: "dongdongdoge/dongdongdoge.github.io"

author:
  name: "Wentao Dong"

include:
  - _pages

exclude:
  - .bundle
  - .github
  - .jekyll-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - run_server.sh
  - vendor

encoding: "utf-8"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: false

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Asia/Hong_Kong

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

compress_html:
  clippings: all
  ignore:
    envs: development
